"""phase2 marketplace exchange rbac otp

Revision ID: 8ef476bf606a
Revises: 6f8be88722b5
Create Date: 2026-08-27 10:26:52.690544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ef476bf606a'
down_revision: Union[str, None] = '6f8be88722b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['marketplace_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('otp_codes',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_phone'), 'otp_codes', ['phone'], unique=False)
    op.create_table('permissions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_table('conversations',
    sa.Column('listing_type', sa.String(length=20), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_type', 'listing_id', 'buyer_id', name='uq_conversation_listing_buyer')
    )
    op.create_index(op.f('ix_conversations_buyer_id'), 'conversations', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_listing_id'), 'conversations', ['listing_id'], unique=False)
    op.create_index(op.f('ix_conversations_seller_id'), 'conversations', ['seller_id'], unique=False)
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_table('exchange_listings',
    sa.Column('seller_user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_negotiable', sa.Boolean(), nullable=False),
    sa.Column('condition', sa.String(length=10), nullable=False),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('moderation_status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['marketplace_categories.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['seller_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_listings_category_id'), 'exchange_listings', ['category_id'], unique=False)
    op.create_index(op.f('ix_exchange_listings_expires_at'), 'exchange_listings', ['expires_at'], unique=False)
    op.create_index(op.f('ix_exchange_listings_location_id'), 'exchange_listings', ['location_id'], unique=False)
    op.create_index(op.f('ix_exchange_listings_moderation_status'), 'exchange_listings', ['moderation_status'], unique=False)
    op.create_index(op.f('ix_exchange_listings_seller_user_id'), 'exchange_listings', ['seller_user_id'], unique=False)
    op.create_index(op.f('ix_exchange_listings_status'), 'exchange_listings', ['status'], unique=False)
    op.create_index(op.f('ix_exchange_listings_tenant_id'), 'exchange_listings', ['tenant_id'], unique=False)
    op.create_table('listing_favorites',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('listing_type', sa.String(length=20), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'listing_type', 'listing_id', name='uq_favorite_user_listing')
    )
    op.create_index(op.f('ix_listing_favorites_listing_id'), 'listing_favorites', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_favorites_user_id'), 'listing_favorites', ['user_id'], unique=False)
    op.create_table('listing_reports',
    sa.Column('listing_type', sa.String(length=20), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('reporter_user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_reports_listing_id'), 'listing_reports', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_reports_reporter_user_id'), 'listing_reports', ['reporter_user_id'], unique=False)
    op.create_index(op.f('ix_listing_reports_status'), 'listing_reports', ['status'], unique=False)
    op.create_index(op.f('ix_listing_reports_tenant_id'), 'listing_reports', ['tenant_id'], unique=False)
    op.create_table('moderation_queue',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_queue_entity_id'), 'moderation_queue', ['entity_id'], unique=False)
    op.create_index(op.f('ix_moderation_queue_entity_type'), 'moderation_queue', ['entity_type'], unique=False)
    op.create_index(op.f('ix_moderation_queue_location_id'), 'moderation_queue', ['location_id'], unique=False)
    op.create_index(op.f('ix_moderation_queue_status'), 'moderation_queue', ['status'], unique=False)
    op.create_index(op.f('ix_moderation_queue_tenant_id'), 'moderation_queue', ['tenant_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('seller_reviews',
    sa.Column('seller_user_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_user_id', sa.UUID(), nullable=False),
    sa.Column('listing_type', sa.String(length=20), nullable=True),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seller_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_user_id', 'reviewer_user_id', 'listing_type', 'listing_id', name='uq_review_per_listing')
    )
    op.create_index(op.f('ix_seller_reviews_reviewer_user_id'), 'seller_reviews', ['reviewer_user_id'], unique=False)
    op.create_index(op.f('ix_seller_reviews_seller_user_id'), 'seller_reviews', ['seller_user_id'], unique=False)
    op.create_index(op.f('ix_seller_reviews_tenant_id'), 'seller_reviews', ['tenant_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('scope_location_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'scope_location_id', name='uq_user_role_scope')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_scope_location_id'), 'user_roles', ['scope_location_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('user_trust_scores',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_listings', sa.Integer(), nullable=False),
    sa.Column('total_reports', sa.Integer(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('marketplace_products',
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('seller_user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('condition', sa.String(length=10), nullable=False),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('moderation_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['marketplace_categories.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['seller_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_products_business_id'), 'marketplace_products', ['business_id'], unique=False)
    op.create_index(op.f('ix_marketplace_products_category_id'), 'marketplace_products', ['category_id'], unique=False)
    op.create_index(op.f('ix_marketplace_products_location_id'), 'marketplace_products', ['location_id'], unique=False)
    op.create_index(op.f('ix_marketplace_products_moderation_status'), 'marketplace_products', ['moderation_status'], unique=False)
    op.create_index(op.f('ix_marketplace_products_seller_user_id'), 'marketplace_products', ['seller_user_id'], unique=False)
    op.create_index(op.f('ix_marketplace_products_status'), 'marketplace_products', ['status'], unique=False)
    op.create_index(op.f('ix_marketplace_products_tenant_id'), 'marketplace_products', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.add_column('businesses', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_businesses_tenant_id'), 'businesses', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_hospitals_tenant_id'), 'hospitals', ['tenant_id'], unique=False)
    op.add_column('locations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_markets_tenant_id'), 'markets', ['tenant_id'], unique=False)
    op.add_column('news_articles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('place_reviews', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('places', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_places_tenant_id'), 'places', ['tenant_id'], unique=False)
    op.add_column('refresh_tokens', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('services', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_services_tenant_id'), 'services', ['tenant_id'], unique=False)
    op.add_column('tenants', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # Phase 1 shipped a two-value role column; map it onto the Section 5.12 role names.
    op.execute("UPDATE users SET role = 'super_admin' WHERE role = 'admin'")
    op.execute("UPDATE users SET role = 'content_editor' WHERE role = 'editor'")


def downgrade() -> None:
    op.execute("UPDATE users SET role = 'admin' WHERE role = 'super_admin'")
    op.execute("UPDATE users SET role = 'editor' WHERE role = 'content_editor'")
    # Other Phase 2 roles have no Phase 1 equivalent; they lose staff access on downgrade.
    op.execute("UPDATE users SET role = 'user' WHERE role NOT IN ('admin', 'editor', 'user')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('tenants', 'updated_at')
    op.drop_index(op.f('ix_services_tenant_id'), table_name='services')
    op.drop_column('services', 'updated_at')
    op.drop_column('refresh_tokens', 'updated_at')
    op.drop_index(op.f('ix_places_tenant_id'), table_name='places')
    op.drop_column('places', 'updated_at')
    op.drop_column('place_reviews', 'updated_at')
    op.drop_column('news_articles', 'updated_at')
    op.drop_index(op.f('ix_markets_tenant_id'), table_name='markets')
    op.drop_column('locations', 'updated_at')
    op.drop_index(op.f('ix_hospitals_tenant_id'), table_name='hospitals')
    op.drop_index(op.f('ix_businesses_tenant_id'), table_name='businesses')
    op.drop_column('businesses', 'updated_at')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_marketplace_products_tenant_id'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_status'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_seller_user_id'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_moderation_status'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_location_id'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_category_id'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_business_id'), table_name='marketplace_products')
    op.drop_table('marketplace_products')
    op.drop_table('user_trust_scores')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_scope_location_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_seller_reviews_tenant_id'), table_name='seller_reviews')
    op.drop_index(op.f('ix_seller_reviews_seller_user_id'), table_name='seller_reviews')
    op.drop_index(op.f('ix_seller_reviews_reviewer_user_id'), table_name='seller_reviews')
    op.drop_table('seller_reviews')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_moderation_queue_tenant_id'), table_name='moderation_queue')
    op.drop_index(op.f('ix_moderation_queue_status'), table_name='moderation_queue')
    op.drop_index(op.f('ix_moderation_queue_location_id'), table_name='moderation_queue')
    op.drop_index(op.f('ix_moderation_queue_entity_type'), table_name='moderation_queue')
    op.drop_index(op.f('ix_moderation_queue_entity_id'), table_name='moderation_queue')
    op.drop_table('moderation_queue')
    op.drop_index(op.f('ix_listing_reports_tenant_id'), table_name='listing_reports')
    op.drop_index(op.f('ix_listing_reports_status'), table_name='listing_reports')
    op.drop_index(op.f('ix_listing_reports_reporter_user_id'), table_name='listing_reports')
    op.drop_index(op.f('ix_listing_reports_listing_id'), table_name='listing_reports')
    op.drop_table('listing_reports')
    op.drop_index(op.f('ix_listing_favorites_user_id'), table_name='listing_favorites')
    op.drop_index(op.f('ix_listing_favorites_listing_id'), table_name='listing_favorites')
    op.drop_table('listing_favorites')
    op.drop_index(op.f('ix_exchange_listings_tenant_id'), table_name='exchange_listings')
    op.drop_index(op.f('ix_exchange_listings_status'), table_name='exchange_listings')
    op.drop_index(op.f('ix_exchange_listings_seller_user_id'), table_name='exchange_listings')
    op.drop_index(op.f('ix_exchange_listings_moderation_status'), table_name='exchange_listings')
    op.drop_index(op.f('ix_exchange_listings_location_id'), table_name='exchange_listings')
    op.drop_index(op.f('ix_exchange_listings_expires_at'), table_name='exchange_listings')
    op.drop_index(op.f('ix_exchange_listings_category_id'), table_name='exchange_listings')
    op.drop_table('exchange_listings')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_seller_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_listing_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_buyer_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_otp_codes_phone'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_table('marketplace_categories')
    # ### end Alembic commands ###
